# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_auto_20160525_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Todo.Categoria'),
        ),
    ]
